server:
  port: 8082

spring:
  config:
    import: "optional:configserver:http://127.0.0.1:8081/"
  application:
    name: server1
  profiles:
    active: local

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
  secrete-key: ${JASYPT_SECRET_KEY}